modLoader="javafml"
loaderVersion="[52,)"
license="GPLv3"
issueTrackerURL="https://github.com/Hantonik/FancyBlockParticles/issues"

clientSideOnly=true

[[mods]]
    modId="fbp"
    version="${mod_version}"
    displayName="${mod_name}"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/fbp-renewed"
    logoFile="logo.png"
    updateJSONURL="https://raw.githubusercontent.com/Hantonik/FancyBlockParticles/${mc_version}/update.json"
    authors="Hantonik, TominoCZ"
    credits="Original mod by TominoCZ"
    description='''3D Digging particles! YAY!'''

[[dependencies.fbp]]
    modId="forge"
    mandatory=true
    versionRange="[52,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.fbp]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="CLIENT"
