# Gradle
org.gradle.jvmargs = -Xmx4G -Xms4G
org.gradle.daemon = false

# Mod Properties
mod_id = fbp
mod_name = FancyBlockParticles

mod_version_label = release

# Mappings
mappings_channel = parchment
mappings_version = 2025.03.23

# Minecraft
mc_version = 1.21.4

neo_version = 21.4.155

loader_version = 0.18.1
fabric_version = 0.119.4

java_version = 21

# Dependencies
modmenu_version = 13.0.3

sereneseasons_version = 10.4.0.6
glitchcore_version = 2.3.0.4

sodium_version = 0.6.13
iris_version = 1.8.8

embeddium_version = 1.0.12-beta.431
oculus_version = 1.20.1-1.7.0

spark_version = 1.10.121

mixin_extras_version = 0.4.1

lombok_version = 1.18.+