# Gradle
org.gradle.jvmargs = -Xmx4G -Xms4G
org.gradle.daemon = false

# Mod Properties
mod_id = fbp
mod_name = FancyBlockParticles

mod_version_label = beta

# Minecraft
mc_version = 26.1.2

neo_version = 26.1.2.66-beta

loader_version = 0.19.2
fabric_version = 0.149.1

java_version = 25

# Dependencies
modmenu_version = 18.0.0-beta.1

sereneseasons_version = 26.1.2.0.2
glitchcore_version = 26.1.2.0.2

sodium_version = 0.8.12
iris_version = 1.10.9

embeddium_version = 1.0.12-beta.431
oculus_version = 1.20.1-1.7.0

spark_version = 1.10.172

mixin_extras_version = 0.5.4

lombok_version = 1.18.+