modLoader="javafml"
loaderVersion="[4,)"
license="GPLv3"
issueTrackerURL="https://github.com/Hantonik/FancyBlockParticles/issues"

[[mods]]
    modId="fbp"
    version="${mod_version}"
    displayName="${mod_name}"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/fbp-renewed"
    displayTest="IGNORE_ALL_VERSION"
    logoFile="logo.png"
    updateJSONURL="https://raw.githubusercontent.com/Hantonik/FancyBlockParticles/${mc_version}/update.json"
    authors="Hantonik, TominoCZ"
    credits="Original mod by TominoCZ"
    description='''3D Digging particles! YAY!'''

[[mixins]]
    config="${mod_id}.mixins.json"

[[dependencies.fbp]]
    modId="neoforge"
    type="required"
    versionRange="[21.1,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.fbp]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="CLIENT"
